name: flutter_map_dragmarker
description: Dragmarker class for flutter_map
version: 5.0.0
repository: https://github.com/ibrierley/flutter_map_dragmarker

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ">=5.0.0 <6.0.0"
  latlong2: ">=0.8.0 <0.10.0"

dev_dependencies:
  flutter_lints: ">=1.0.4"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
